spring:
  application:
    name: gcp-discord-bot
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"

logging:
  level:
    web: debug

extension:
  discord:
    ownerId: dummyId
    token: dummyToken
